# Generated by Django 3.2.5 on 2022-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('last_updated_at', models.CharField(max_length=50)),
            ],
        ),
    ]
